# Generated by Django 3.2.12 on 2022-05-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('studentid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='images')),
            ],
        ),
    ]
